In [3]:
import numpy as np
import time

In [4]:
# Coverting a list to a NumPy Array
array = np.array([1, 2, 3, 4, 5])


## Python Lists vs NumPy Arrays 
- NumPy Arrays are faster (optimized in C)
- NUmpy stores data in continuous memory blocks
- Uses less memory (optimized storage)
- Built in Mathematical Functions 
- Supports direct vectorized operations


In [5]:
# Execution Time Performace Comparison

size = 1_000_000

# Python List
py_list = list(range(size)) # [1, 2, 3, 4, .....1,000,000]
start = time.time() # Current time
sq_list = [x ** 2 for x in py_list]
end = time.time() # Time after calculating squares
print(f"Python List Time = {end - start} seconds")

# NumPy Array
np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2 # Used vectorization
end = time.time()
print(f"NumPy Array Time = {end - start} seconds")


Python List Time = 3.0845448970794678 seconds
NumPy Array Time = 0.31664586067199707 seconds


In [6]:
# Memory Occupied Comparison

import sys
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy Array size = {np_array.nbytes} bytes")

Python list size = 80000005600000000 bytes
NumPy Array size = 800000000 bytes


In [13]:
# Create NumPy Arrays - From lists 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr1.shape) # Shape stands for dimension (m X n)

arr2 = np.array([1, 2, 3, 4, 5, "Adi"])
print(arr2, type[arr2], arr2.dtype, arr2.shape)

# 2D Arrays - Matrix
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape) # (4 x 3)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Adi'] type[array(['1', '2', '3', '4', '5', 'Adi'], dtype='<U21')] <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
