In [1]:
import numpy as np
import time

In [2]:
# Coverting a list to a NumPy Array
array = np.array([1, 2, 3, 4, 5])


## Python Lists vs NumPy Arrays 
- NumPy Arrays are faster (optimized in C)
- NUmpy stores data in continuous memory blocks
- Uses less memory (optimized storage)
- Built in Mathematical Functions 
- Supports direct vectorized operations


In [3]:
# Execution Time Performace Comparison

size = 1_000_000

# Python List
py_list = list(range(size)) # [1, 2, 3, 4, .....1,000,000]
start = time.time() # Current time
sq_list = [x ** 2 for x in py_list]
end = time.time() # Time after calculating squares
print(f"Python List Time = {end - start} seconds")

# NumPy Array
np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2 # Used vectorization
end = time.time()
print(f"NumPy Array Time = {end - start} seconds")


Python List Time = 0.04884815216064453 seconds
NumPy Array Time = 0.0019180774688720703 seconds


In [4]:
# Memory Occupied Comparison

import sys
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy Array size = {np_array.nbytes} bytes")

Python list size = 8000056000000 bytes
NumPy Array size = 8000000 bytes


In [5]:
# Create NumPy Arrays - From lists 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1), arr1.shape) # Shape stands for dimension (m X n)

arr2 = np.array([1, 2, 3, 4, 5, "Adi"])
print(arr2, type[arr2], arr2.dtype, arr2.shape)

# 2D Arrays - Matrix
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape) # (4 x 3)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Adi'] type[array(['1', '2', '3', '4', '5', 'Adi'], dtype='<U21')] <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [6]:
# Create NumPy Arrays from Scratch 

arr1 = np.zeros((2,3)) # Prefill with 0s
print(f"arr1: \n {arr1}, {arr1.shape}")

arr2 = np.zeros((2,3), dtype = "int64")
print(f"arr2: \n {arr2}, {arr2.shape}")

arr3 = np.ones((2,3), dtype = "int64") # Prefill with 1s
print(f"arr3: \n {arr3}, {arr3.shape}")

arr4 = np.full((3, 4), 100) # Prefill with 100s
print(f"arr4: \n {arr4}")

arr5 = np.eye(5, dtype = "int64") # Creates an Identity Matrix
print(f"arr5: \n {arr5}")

arr6 = np.arange(1, 10) # Creates an array of numbers from 1 to 9 (Works similar to range())
print(f"arr6: \n {arr6}")

arr7 = np.linspace(1, 100, 4) # We want an array of size 4 that lies in the range of 1 to 100
print(f"arr7: \n {arr7}") # The values obtained are evenly spaced.

arr1: 
 [[0. 0. 0.]
 [0. 0. 0.]], (2, 3)
arr2: 
 [[0 0 0]
 [0 0 0]], (2, 3)
arr3: 
 [[1 1 1]
 [1 1 1]], (2, 3)
arr4: 
 [[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
arr5: 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
arr6: 
 [1 2 3 4 5 6 7 8 9]
arr7: 
 [  1.  34.  67. 100.]


In [7]:
# NumPy Array Properties
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.shape) # dimensions of arr (2, 5)
print(arr.size) # Total number of elements 
print(arr.dtype) # int64
print(arr.ndim) # Number of dimensions

# Type Casting
float_arr = arr.astype(np.float64) # A new array with data type of float64
print(float_arr, float_arr.dtype)

(2, 5)
10
int64
2
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]] float64


---

## Operations on NumPy Arrays
- Reshaping
- Indexing (1D and 2D Array)
- Fancy and Boolean Indexing
- Slicing

In [8]:
# Reshaping - Change the dimensions
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2)) # Change from (2, 3) to (3, 2)
print(reshaped, reshaped.shape)

# Flattened - Convert to a 1D Array
flattened = reshaped.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [12]:
# Indexing
arr1 = np.array([1, 2, 3, 4, 5]) # 1D Array
print(arr[0], arr[3]) 
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D Array
print(arr2[0, 2], arr2[1, 1])

# Fancy Indexing (Can access a particular set of indexes together)
idx = [0, 1, 3]
print(arr1[idx])

# Boolean Indexing
print(arr1[arr1 > 2]) # Array values greater than 2
print(arr1[arr1 % 2 == 0]) # Even array values

1 4
3 5
[1 2 4]
[3 4 5]
[2 4]


In [13]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) #[3, 4, 5, 6]
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


In [15]:
# Copy vs View by slicing
# Sliced list is a copy
# Sliced array is a view (We are looking at the original values and not a new copy
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)
# Only the sub_list changes, the nums list does not change

arr = np.array([1, 2, 3, 4, 5, 6, 7])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)
# Both the sub array and the main array changed

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5   6   7]


 # NumPy Common Data Types 
 - Integers: <i><b>int32, int64</b></i>
 - Floating point nums: <i><b>float32, float64</b></i>
 - Boolean: <i><b>bool</b></i>
 - Complex Nums: <i><b>complex64, complex128</b></i>
 - String: <i><b>S</b></i> (byte-str) & <i><b>U</b></i> (unicode-str)
 - Object: generic python objects - <i><b>object</b></i>

In [19]:
# Data Types 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, arr1.dtype)
arr2 = np.array([1, 2, 3.4, 4, 5])
print(arr2, arr2.dtype)
arr3 = np.array(["hello", "world", "Adi", "tree"])
print(arr3, arr3.dtype)

# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)    

'''
Better to not use String and Object data types in NumPy as NumPy is meant
for numerical computation.
'''
# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

[1 2 3 4 5] int64
[1.  2.  3.4 4.  5. ] float64
['hello' 'world' 'Adi' 'tree'] <U5
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
